services:
  - type: web
    name: editscape-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:create_app() --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        sync: false
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USE_TLS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
