"""Add media fields to PortfolioItem

Revision ID: 484513fcba4a
Revises: 8c133bbc8139
Create Date: 2025-07-28 23:42:14.814042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484513fcba4a'
down_revision = '8c133bbc8139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_item', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
